import pygame


SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 900
FPS = 30
DINO_X_POS = 80
DINO_Y_POS = 310
GRAVITY = 0.8
JUMP_VELOCITY = 8.5
COUCHING_HEIGHT = 60
STAND_HEIGHT = 80
BACKGROUND_Y = 380
IMAGE_WIDTH = 87
IMAGE_HEIGHT = 94

STANDER_RECT= pygame.Rect(DINO_X_POS, DINO_Y_POS, IMAGE_WIDTH, IMAGE_HEIGHT)

INITIAL_GAME_SPEED = 20
NUMBER_OF_GENERATIONS = 200
NUMBER_OF_POPULATION=300
SAVE_DIR = "dino_saves"
OLD_DIR = "old_saves"

SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
